/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.*;

/**
 *
 * @author SilentLamb
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(550,400);
        this.setResizable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("登录名");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 110, 80, 40);

        jTextField_username.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_username);
        jTextField_username.setBounds(220, 120, 240, 30);

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setText("密码");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 190, 70, 30);

        jButton1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jButton1.setText("登陆");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 260, 170, 40);

        jPasswordField_password.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jPasswordField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField_password);
        jPasswordField_password.setBounds(220, 190, 240, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_passwordActionPerformed

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String driverName="com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String dbsURL="jdbc:sqlserver://localhost\\SQLEXPRESS:1433;DatabaseName=MyContactsDBS";
        String userName="sa";
        String userPwd="zouqichen525200";

        try{
            Class.forName(driverName);
            Connection dbsConnection=DriverManager.getConnection(dbsURL,userName,userPwd);
            System.out.println("连接数据库成功");
            Statement checkconnection = dbsConnection.createStatement();
            String _username = jTextField_username.getText();
            String _userpassword = String.valueOf(jPasswordField_password.getPassword());
            String sql = "SELECT username,userpassword FROM MyAdmin WHERE username = '" 
                    + _username + "' and userpassword = '" + _userpassword + "'";
            ResultSet rs = checkconnection.executeQuery(sql);
            String password = null;
            while(rs.next()){
                password = rs.getString("userpassword");
            }
            //System.out.println(password);
            //System.out.println(_userpassword);
            if (_userpassword.equals(password)) {
                System.out.println("success");
                new ReadingPage();
            }
            else {
                System.out.println("failure");
            }
            rs.close();

        }
        catch(Exception e) {
            e.printStackTrace();
            System.out.print("连接失败");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
